# encoding: UTF-8
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# Note that this schema.rb definition is the authoritative source for your
# database schema. If you need to create the application database on another
# system, you should be using db:schema:load, not running all the migrations
# from scratch. The latter is a flawed and unsustainable approach (the more migrations
# you'll amass, the slower it'll run and the greater likelihood for issues).
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema.define(version: 20141203050123) do

  # These are extensions that must be enabled in order to support this database
  enable_extension "plpgsql"

  create_table "conservations", force: true do |t|
    t.integer  "number_of_species"
    t.string   "clades"
    t.string   "fname"
    t.text     "url"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "datasets", force: true do |t|
    t.text     "data"
    t.string   "dbname"
    t.text     "link"
    t.text     "columns"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "fantom_fives", force: true do |t|
    t.text     "biological_category"
    t.text     "technology"
    t.text     "extract_name"
    t.text     "comment__rna_tube_"
    t.text     "comment__sample_name_"
    t.text     "comment__organism_"
    t.text     "protocol_ref"
    t.text     "parameter__rna_extraction_"
    t.text     "extract_name_1"
    t.text     "comment__rna_id_"
    t.text     "comment__material_type_"
    t.text     "comment__comment_on_rna_"
    t.text     "protocol_ref_1"
    t.text     "comment__lsid_"
    t.text     "parameter__library_protocol_"
    t.text     "library_name"
    t.text     "comment__library_id_"
    t.text     "protocol_ref_2"
    t.text     "parameter__sequence_protocol_"
    t.text     "parameter__machine_name_"
    t.text     "parameter__run_name_"
    t.text     "parameter__flowcell_channel_"
    t.text     "file_name"
    t.text     "comment__sequence_raw_file_"
    t.text     "protocol_ref_3"
    t.text     "parameter__sex_"
    t.text     "file_name_1"
    t.text     "fname"
    t.text     "url"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "human_meta_tracks", force: true do |t|
    t.text     "cell_type"
    t.text     "region_type"
    t.text     "other"
    t.text     "fname"
    t.text     "internal_name"
    t.text     "url"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "queries", force: true do |t|
    t.string   "job_id"
    t.text     "user_query"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "user_id",    default: 0
    t.string   "token",                      null: false
    t.boolean  "shared",     default: false
    t.string   "name"
  end

  add_index "queries", ["user_id"], name: "index_queries_on_user_id", using: :btree

  create_table "roadmaps", force: true do |t|
    t.text     "cell_type"
    t.text     "experiment"
    t.text     "fname"
    t.text     "url"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "snps", force: true do |t|
    t.integer  "build_number"
    t.string   "feature"
    t.string   "fname"
    t.text     "url"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "tracks", force: true do |t|
    t.text     "fname"
    t.integer  "user_id"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.integer  "fsize"
  end

  add_index "tracks", ["user_id"], name: "index_tracks_on_user_id", using: :btree

  create_table "users", force: true do |t|
    t.string   "email",                  default: "", null: false
    t.string   "encrypted_password",     default: "", null: false
    t.string   "reset_password_token"
    t.datetime "reset_password_sent_at"
    t.datetime "remember_created_at"
    t.integer  "sign_in_count",          default: 0,  null: false
    t.datetime "current_sign_in_at"
    t.datetime "last_sign_in_at"
    t.inet     "current_sign_in_ip"
    t.inet     "last_sign_in_ip"
    t.string   "confirmation_token"
    t.datetime "confirmed_at"
    t.datetime "confirmation_sent_at"
    t.datetime "created_at"
    t.datetime "updated_at"
    t.string   "db_name"
    t.integer  "file_size",              default: 0
  end

  add_index "users", ["confirmation_token"], name: "index_users_on_confirmation_token", unique: true, using: :btree
  add_index "users", ["email"], name: "index_users_on_email", unique: true, using: :btree
  add_index "users", ["reset_password_token"], name: "index_users_on_reset_password_token", unique: true, using: :btree

  create_table "wg_encode_affy_rna_chips", force: true do |t|
    t.text     "cell"
    t.text     "composite"
    t.text     "data_type"
    t.text     "data_version"
    t.text     "date_submitted"
    t.text     "date_unrestricted"
    t.text     "dcc_accession"
    t.text     "grant"
    t.text     "lab"
    t.text     "localization"
    t.text     "md5sum"
    t.text     "orig_assembly"
    t.text     "project"
    t.text     "rna_extract"
    t.text     "size"
    t.text     "sub_id"
    t.text     "table_name"
    t.text     "type"
    t.text     "view"
    t.text     "filename"
    t.text     "fname"
    t.text     "url"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "wg_encode_broad_histones", force: true do |t|
    t.text     "antibody"
    t.text     "cell"
    t.text     "composite"
    t.text     "control"
    t.text     "control_id"
    t.text     "data_type"
    t.text     "data_version"
    t.text     "date_resubmitted"
    t.text     "date_submitted"
    t.text     "date_unrestricted"
    t.text     "dcc_accession"
    t.text     "geo_sample_accession"
    t.text     "grant"
    t.text     "lab"
    t.text     "lab_version"
    t.text     "md5sum"
    t.text     "obj_status"
    t.text     "orig_assembly"
    t.text     "project"
    t.text     "replicate"
    t.text     "seq_platform"
    t.text     "set_type"
    t.text     "sex"
    t.text     "size"
    t.text     "software_version"
    t.text     "sub_id"
    t.text     "submitted_data_version"
    t.text     "table_name"
    t.text     "treatment"
    t.text     "type"
    t.text     "view"
    t.text     "filename"
    t.text     "fname"
    t.text     "url"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "wg_encode_broad_hmms", force: true do |t|
    t.text     "cell"
    t.text     "composite"
    t.text     "data_type"
    t.text     "data_version"
    t.text     "date_submitted"
    t.text     "date_unrestricted"
    t.text     "dcc_accession"
    t.text     "geo_sample_accession"
    t.text     "grant"
    t.text     "lab"
    t.text     "md5sum"
    t.text     "orig_assembly"
    t.text     "project"
    t.text     "size"
    t.text     "software_version"
    t.text     "sub_id"
    t.text     "table_name"
    t.text     "type"
    t.text     "view"
    t.text     "filename"
    t.text     "fname"
    t.text     "url"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "wg_encode_cshl_long_rna_seqs", force: true do |t|
    t.text     "bio_rep"
    t.text     "cell"
    t.text     "composite"
    t.text     "data_type"
    t.text     "data_version"
    t.text     "date_resubmitted"
    t.text     "date_submitted"
    t.text     "date_unrestricted"
    t.text     "dcc_accession"
    t.text     "dcc_internal_notes"
    t.text     "donor_id"
    t.text     "geo_sample_accession"
    t.text     "grant"
    t.text     "lab"
    t.text     "lab_exp_id"
    t.text     "lab_protocol_id"
    t.text     "lab_version"
    t.text     "localization"
    t.text     "md5sum"
    t.text     "obj_status"
    t.text     "project"
    t.text     "read_type"
    t.text     "replicate"
    t.text     "rna_extract"
    t.text     "seq_platform"
    t.text     "sex"
    t.text     "size"
    t.text     "spike_in_pool"
    t.text     "sub_id"
    t.text     "submitted_data_version"
    t.text     "table_name"
    t.text     "type"
    t.text     "view"
    t.text     "filename"
    t.text     "fname"
    t.text     "url"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "wg_encode_cshl_short_rna_seqs", force: true do |t|
    t.text     "bio_rep"
    t.text     "cell"
    t.text     "composite"
    t.text     "data_type"
    t.text     "data_version"
    t.text     "date_resubmitted"
    t.text     "date_submitted"
    t.text     "date_unrestricted"
    t.text     "dcc_accession"
    t.text     "donor_id"
    t.text     "geo_sample_accession"
    t.text     "grant"
    t.text     "lab"
    t.text     "lab_exp_id"
    t.text     "lab_protocol_id"
    t.text     "lab_version"
    t.text     "localization"
    t.text     "md5sum"
    t.text     "obj_status"
    t.text     "orig_assembly"
    t.text     "project"
    t.text     "protocol"
    t.text     "read_type"
    t.text     "replicate"
    t.text     "rna_extract"
    t.text     "seq_platform"
    t.text     "sex"
    t.text     "size"
    t.text     "sub_id"
    t.text     "submitted_data_version"
    t.text     "table_name"
    t.text     "type"
    t.text     "view"
    t.text     "filename"
    t.text     "fname"
    t.text     "url"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "wg_encode_duke_affy_exons", force: true do |t|
    t.text     "cell"
    t.text     "composite"
    t.text     "data_type"
    t.text     "data_version"
    t.text     "date_resubmitted"
    t.text     "date_submitted"
    t.text     "date_unrestricted"
    t.text     "dcc_accession"
    t.text     "geo_sample_accession"
    t.text     "grant"
    t.text     "lab"
    t.text     "lab_version"
    t.text     "md5sum"
    t.text     "obj_status"
    t.text     "orig_assembly"
    t.text     "project"
    t.text     "replicate"
    t.text     "sex"
    t.text     "size"
    t.text     "sub_id"
    t.text     "submitted_data_version"
    t.text     "table_name"
    t.text     "treatment"
    t.text     "type"
    t.text     "view"
    t.text     "filename"
    t.text     "fname"
    t.text     "url"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "wg_encode_gencodes", force: true do |t|
    t.text     "version"
    t.text     "features"
    t.text     "fname"
    t.text     "url"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "wg_encode_gis_chia_pets", force: true do |t|
    t.text     "antibody"
    t.text     "cell"
    t.text     "composite"
    t.text     "data_type"
    t.text     "data_version"
    t.text     "date_resubmitted"
    t.text     "date_submitted"
    t.text     "date_unrestricted"
    t.text     "dcc_accession"
    t.text     "geo_sample_accession"
    t.text     "grant"
    t.text     "lab"
    t.text     "lab_exp_id"
    t.text     "md5sum"
    t.text     "project"
    t.text     "replicate"
    t.text     "size"
    t.text     "sub_id"
    t.text     "table_name"
    t.text     "type"
    t.text     "view"
    t.text     "filename"
    t.text     "fname"
    t.text     "url"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "wg_encode_gis_rna_pets", force: true do |t|
    t.text     "bio_rep"
    t.text     "cell"
    t.text     "composite"
    t.text     "data_type"
    t.text     "data_version"
    t.text     "date_resubmitted"
    t.text     "date_submitted"
    t.text     "date_unrestricted"
    t.text     "dcc_accession"
    t.text     "donor_id"
    t.text     "geo_sample_accession"
    t.text     "grant"
    t.text     "lab"
    t.text     "lab_exp_id"
    t.text     "lab_version"
    t.text     "localization"
    t.text     "md5sum"
    t.text     "obj_status"
    t.text     "orig_assembly"
    t.text     "project"
    t.text     "read_type"
    t.text     "replicate"
    t.text     "rna_extract"
    t.text     "seq_platform"
    t.text     "size"
    t.text     "sub_id"
    t.text     "submitted_data_version"
    t.text     "table_name"
    t.text     "type"
    t.text     "view"
    t.text     "filename"
    t.text     "fname"
    t.text     "url"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "wg_encode_gis_rna_seqs", force: true do |t|
    t.text     "bio_rep"
    t.text     "cell"
    t.text     "composite"
    t.text     "data_type"
    t.text     "data_version"
    t.text     "date_resubmitted"
    t.text     "date_submitted"
    t.text     "date_unrestricted"
    t.text     "dcc_accession"
    t.text     "geo_sample_accession"
    t.text     "grant"
    t.text     "lab"
    t.text     "lab_exp_id"
    t.text     "lab_protocol_id"
    t.text     "localization"
    t.text     "md5sum"
    t.text     "orig_assembly"
    t.text     "project"
    t.text     "replicate"
    t.text     "rna_extract"
    t.text     "size"
    t.text     "sub_id"
    t.text     "table_name"
    t.text     "type"
    t.text     "view"
    t.text     "filename"
    t.text     "fname"
    t.text     "url"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "wg_encode_haib_rna_seqs", force: true do |t|
    t.text     "cell"
    t.text     "composite"
    t.text     "data_type"
    t.text     "data_version"
    t.text     "date_submitted"
    t.text     "date_unrestricted"
    t.text     "dcc_accession"
    t.text     "geo_sample_accession"
    t.text     "grant"
    t.text     "lab"
    t.text     "lab_exp_id"
    t.text     "lab_version"
    t.text     "map_algorithm"
    t.text     "md5sum"
    t.text     "obj_status"
    t.text     "orig_assembly"
    t.text     "project"
    t.text     "read_type"
    t.text     "replicate"
    t.text     "rna_extract"
    t.text     "sex"
    t.text     "size"
    t.text     "sub_id"
    t.text     "submitted_data_version"
    t.text     "table_name"
    t.text     "treatment"
    t.text     "type"
    t.text     "view"
    t.text     "filename"
    t.text     "fname"
    t.text     "url"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "wg_encode_haib_tfbs", force: true do |t|
    t.text     "antibody"
    t.text     "cell"
    t.text     "composite"
    t.text     "control_id"
    t.text     "data_type"
    t.text     "data_version"
    t.text     "date_resubmitted"
    t.text     "date_submitted"
    t.text     "date_unrestricted"
    t.text     "dcc_accession"
    t.text     "geo_sample_accession"
    t.text     "grant"
    t.text     "lab"
    t.text     "lab_exp_id"
    t.text     "lab_version"
    t.text     "md5sum"
    t.text     "obj_status"
    t.text     "orig_assembly"
    t.text     "project"
    t.text     "protocol"
    t.text     "replicate"
    t.text     "set_type"
    t.text     "size"
    t.text     "software_version"
    t.text     "sub_id"
    t.text     "submitted_data_version"
    t.text     "table_name"
    t.text     "treatment"
    t.text     "type"
    t.text     "view"
    t.text     "filename"
    t.text     "fname"
    t.text     "url"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "wg_encode_open_chrom_chips", force: true do |t|
    t.text     "antibody"
    t.text     "cell"
    t.text     "composite"
    t.text     "control_id"
    t.text     "data_type"
    t.text     "data_version"
    t.text     "date_resubmitted"
    t.text     "date_submitted"
    t.text     "date_unrestricted"
    t.text     "dcc_accession"
    t.text     "geo_sample_accession"
    t.text     "grant"
    t.text     "lab"
    t.text     "lab_version"
    t.text     "md5sum"
    t.text     "obj_status"
    t.text     "orig_assembly"
    t.text     "project"
    t.text     "replicate"
    t.text     "set_type"
    t.text     "size"
    t.text     "sub_id"
    t.text     "table_name"
    t.text     "treatment"
    t.text     "type"
    t.text     "view"
    t.text     "filename"
    t.text     "fname"
    t.text     "url"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "wg_encode_open_chrom_dnases", force: true do |t|
    t.text     "cell"
    t.text     "composite"
    t.text     "control_id"
    t.text     "data_type"
    t.text     "data_version"
    t.text     "date_resubmitted"
    t.text     "date_submitted"
    t.text     "date_unrestricted"
    t.text     "dcc_accession"
    t.text     "geo_sample_accession"
    t.text     "grant"
    t.text     "lab"
    t.text     "lab_version"
    t.text     "md5sum"
    t.text     "obj_status"
    t.text     "orig_assembly"
    t.text     "project"
    t.text     "replicate"
    t.text     "size"
    t.text     "sub_id"
    t.text     "submitted_data_version"
    t.text     "table_name"
    t.text     "treatment"
    t.text     "type"
    t.text     "view"
    t.text     "filename"
    t.text     "fname"
    t.text     "url"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "wg_encode_open_chrom_faires", force: true do |t|
    t.text     "cell"
    t.text     "composite"
    t.text     "control_id"
    t.text     "data_type"
    t.text     "data_version"
    t.text     "date_resubmitted"
    t.text     "date_submitted"
    t.text     "date_unrestricted"
    t.text     "dcc_accession"
    t.text     "geo_sample_accession"
    t.text     "grant"
    t.text     "lab"
    t.text     "lab_version"
    t.text     "md5sum"
    t.text     "obj_status"
    t.text     "orig_assembly"
    t.text     "project"
    t.text     "replicate"
    t.text     "size"
    t.text     "sub_id"
    t.text     "table_name"
    t.text     "treatment"
    t.text     "type"
    t.text     "view"
    t.text     "filename"
    t.text     "fname"
    t.text     "url"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "wg_encode_open_chrom_synths", force: true do |t|
    t.text     "cell"
    t.text     "composite"
    t.text     "data_type"
    t.text     "data_version"
    t.text     "date_submitted"
    t.text     "date_unrestricted"
    t.text     "dcc_accession"
    t.text     "geo_sample_accession"
    t.text     "grant"
    t.text     "lab"
    t.text     "lab_version"
    t.text     "md5sum"
    t.text     "project"
    t.text     "size"
    t.text     "sub_id"
    t.text     "table_name"
    t.text     "treatment"
    t.text     "type"
    t.text     "view"
    t.text     "filename"
    t.text     "fname"
    t.text     "url"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "wg_encode_riken_cages", force: true do |t|
    t.text     "bio_rep"
    t.text     "cell"
    t.text     "composite"
    t.text     "data_type"
    t.text     "data_version"
    t.text     "date_resubmitted"
    t.text     "date_submitted"
    t.text     "date_unrestricted"
    t.text     "dcc_accession"
    t.text     "donor_id"
    t.text     "geo_sample_accession"
    t.text     "grant"
    t.text     "lab"
    t.text     "lab_exp_id"
    t.text     "lab_version"
    t.text     "localization"
    t.text     "md5sum"
    t.text     "obj_status"
    t.text     "project"
    t.text     "read_type"
    t.text     "replicate"
    t.text     "rna_extract"
    t.text     "seq_platform"
    t.text     "sex"
    t.text     "size"
    t.text     "software_version"
    t.text     "sub_id"
    t.text     "submitted_data_version"
    t.text     "table_name"
    t.text     "type"
    t.text     "view"
    t.text     "filename"
    t.text     "fname"
    t.text     "url"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "wg_encode_suny_rip_seqs", force: true do |t|
    t.text     "antibody"
    t.text     "cell"
    t.text     "composite"
    t.text     "data_type"
    t.text     "data_version"
    t.text     "date_submitted"
    t.text     "date_unrestricted"
    t.text     "dcc_accession"
    t.text     "geo_sample_accession"
    t.text     "grant"
    t.text     "lab"
    t.text     "lab_version"
    t.text     "md5sum"
    t.text     "project"
    t.text     "replicate"
    t.text     "size"
    t.text     "sub_id"
    t.text     "table_name"
    t.text     "type"
    t.text     "view"
    t.text     "filename"
    t.text     "fname"
    t.text     "url"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "wg_encode_sydh_histones", force: true do |t|
    t.text     "antibody"
    t.text     "cell"
    t.text     "composite"
    t.text     "control"
    t.text     "control_id"
    t.text     "data_type"
    t.text     "data_version"
    t.text     "date_resubmitted"
    t.text     "date_submitted"
    t.text     "date_unrestricted"
    t.text     "dcc_accession"
    t.text     "geo_sample_accession"
    t.text     "grant"
    t.text     "lab"
    t.text     "lab_version"
    t.text     "md5sum"
    t.text     "obj_status"
    t.text     "orig_assembly"
    t.text     "project"
    t.text     "replicate"
    t.text     "set_type"
    t.text     "size"
    t.text     "sub_id"
    t.text     "table_name"
    t.text     "treatment"
    t.text     "type"
    t.text     "view"
    t.text     "filename"
    t.text     "fname"
    t.text     "url"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "wg_encode_sydh_nsomes", force: true do |t|
    t.text     "cell"
    t.text     "composite"
    t.text     "data_type"
    t.text     "data_version"
    t.text     "date_resubmitted"
    t.text     "date_submitted"
    t.text     "date_unrestricted"
    t.text     "dcc_accession"
    t.text     "geo_sample_accession"
    t.text     "grant"
    t.text     "lab"
    t.text     "md5sum"
    t.text     "obj_status"
    t.text     "orig_assembly"
    t.text     "project"
    t.text     "replicate"
    t.text     "seq_platform"
    t.text     "size"
    t.text     "sub_id"
    t.text     "submitted_data_version"
    t.text     "table_name"
    t.text     "type"
    t.text     "view"
    t.text     "filename"
    t.text     "fname"
    t.text     "url"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "wg_encode_sydh_rna_seqs", force: true do |t|
    t.text     "cell"
    t.text     "composite"
    t.text     "data_type"
    t.text     "data_version"
    t.text     "date_resubmitted"
    t.text     "date_submitted"
    t.text     "date_unrestricted"
    t.text     "dcc_accession"
    t.text     "geo_sample_accession"
    t.text     "grant"
    t.text     "lab"
    t.text     "md5sum"
    t.text     "orig_assembly"
    t.text     "project"
    t.text     "rna_extract"
    t.text     "size"
    t.text     "sub_id"
    t.text     "table_name"
    t.text     "treatment"
    t.text     "type"
    t.text     "view"
    t.text     "filename"
    t.text     "fname"
    t.text     "url"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "wg_encode_sydh_tfbs", force: true do |t|
    t.text     "antibody"
    t.text     "cell"
    t.text     "composite"
    t.text     "control"
    t.text     "control_id"
    t.text     "data_type"
    t.text     "data_version"
    t.text     "date_resubmitted"
    t.text     "date_submitted"
    t.text     "date_unrestricted"
    t.text     "dcc_accession"
    t.text     "geo_sample_accession"
    t.text     "grant"
    t.text     "lab"
    t.text     "lab_version"
    t.text     "md5sum"
    t.text     "obj_status"
    t.text     "orig_assembly"
    t.text     "project"
    t.text     "replicate"
    t.text     "set_type"
    t.text     "size"
    t.text     "software_version"
    t.text     "sub_id"
    t.text     "submitted_data_version"
    t.text     "table_name"
    t.text     "treatment"
    t.text     "type"
    t.text     "view"
    t.text     "filename"
    t.text     "fname"
    t.text     "url"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "wg_encode_uchicago_tfbs", force: true do |t|
    t.text     "antibody"
    t.text     "cell"
    t.text     "composite"
    t.text     "control"
    t.text     "control_id"
    t.text     "data_type"
    t.text     "data_version"
    t.text     "date_submitted"
    t.text     "date_unrestricted"
    t.text     "dcc_accession"
    t.text     "geo_sample_accession"
    t.text     "grant"
    t.text     "lab"
    t.text     "md5sum"
    t.text     "project"
    t.text     "replicate"
    t.text     "seq_platform"
    t.text     "set_type"
    t.text     "size"
    t.text     "sub_id"
    t.text     "table_name"
    t.text     "type"
    t.text     "view"
    t.text     "filename"
    t.text     "fname"
    t.text     "url"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "wg_encode_uw_affy_exon_arrays", force: true do |t|
    t.text     "cell"
    t.text     "composite"
    t.text     "data_type"
    t.text     "data_version"
    t.text     "date_resubmitted"
    t.text     "date_submitted"
    t.text     "date_unrestricted"
    t.text     "dcc_accession"
    t.text     "geo_sample_accession"
    t.text     "grant"
    t.text     "lab"
    t.text     "lab_exp_id"
    t.text     "md5sum"
    t.text     "obj_status"
    t.text     "orig_assembly"
    t.text     "project"
    t.text     "replicate"
    t.text     "size"
    t.text     "sub_id"
    t.text     "submitted_data_version"
    t.text     "table_name"
    t.text     "treatment"
    t.text     "type"
    t.text     "view"
    t.text     "filename"
    t.text     "fname"
    t.text     "url"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "wg_encode_uw_dgfs", force: true do |t|
    t.text     "cell"
    t.text     "composite"
    t.text     "data_type"
    t.text     "data_version"
    t.text     "date_resubmitted"
    t.text     "date_submitted"
    t.text     "date_unrestricted"
    t.text     "dcc_accession"
    t.text     "geo_sample_accession"
    t.text     "grant"
    t.text     "lab"
    t.text     "lab_exp_id"
    t.text     "lab_version"
    t.text     "md5sum"
    t.text     "obj_status"
    t.text     "orig_assembly"
    t.text     "project"
    t.text     "replicate"
    t.text     "seq_platform"
    t.text     "size"
    t.text     "sub_id"
    t.text     "submitted_data_version"
    t.text     "table_name"
    t.text     "treatment"
    t.text     "type"
    t.text     "view"
    t.text     "filename"
    t.text     "fname"
    t.text     "url"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "wg_encode_uw_dnases", force: true do |t|
    t.text     "cell"
    t.text     "composite"
    t.text     "data_type"
    t.text     "data_version"
    t.text     "date_resubmitted"
    t.text     "date_submitted"
    t.text     "date_unrestricted"
    t.text     "dcc_accession"
    t.text     "geo_sample_accession"
    t.text     "grant"
    t.text     "lab"
    t.text     "lab_exp_id"
    t.text     "lab_version"
    t.text     "md5sum"
    t.text     "obj_status"
    t.text     "orig_assembly"
    t.text     "project"
    t.text     "replicate"
    t.text     "size"
    t.text     "sub_id"
    t.text     "submitted_data_version"
    t.text     "table_name"
    t.text     "treatment"
    t.text     "type"
    t.text     "view"
    t.text     "filename"
    t.text     "fname"
    t.text     "url"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "wg_encode_uw_histones", force: true do |t|
    t.text     "antibody"
    t.text     "cell"
    t.text     "composite"
    t.text     "control"
    t.text     "control_id"
    t.text     "data_type"
    t.text     "data_version"
    t.text     "date_resubmitted"
    t.text     "date_submitted"
    t.text     "date_unrestricted"
    t.text     "dcc_accession"
    t.text     "donor_id"
    t.text     "geo_sample_accession"
    t.text     "grant"
    t.text     "lab"
    t.text     "lab_exp_id"
    t.text     "lab_version"
    t.text     "md5sum"
    t.text     "obj_status"
    t.text     "orig_assembly"
    t.text     "project"
    t.text     "replicate"
    t.text     "set_type"
    t.text     "size"
    t.text     "sub_id"
    t.text     "table_name"
    t.text     "treatment"
    t.text     "type"
    t.text     "view"
    t.text     "filename"
    t.text     "fname"
    t.text     "url"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "wg_encode_uw_repli_seqs", force: true do |t|
    t.text     "cell"
    t.text     "composite"
    t.text     "data_type"
    t.text     "data_version"
    t.text     "date_submitted"
    t.text     "date_unrestricted"
    t.text     "dcc_accession"
    t.text     "geo_sample_accession"
    t.text     "grant"
    t.text     "lab"
    t.text     "lab_exp_id"
    t.text     "md5sum"
    t.text     "orig_assembly"
    t.text     "phase"
    t.text     "project"
    t.text     "replicate"
    t.text     "sex"
    t.text     "size"
    t.text     "sub_id"
    t.text     "table_name"
    t.text     "type"
    t.text     "view"
    t.text     "filename"
    t.text     "fname"
    t.text     "url"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

  create_table "wg_encode_uw_tfbs", force: true do |t|
    t.text     "antibody"
    t.text     "cell"
    t.text     "composite"
    t.text     "control"
    t.text     "control_id"
    t.text     "data_type"
    t.text     "data_version"
    t.text     "date_resubmitted"
    t.text     "date_submitted"
    t.text     "date_unrestricted"
    t.text     "dcc_accession"
    t.text     "donor_id"
    t.text     "geo_sample_accession"
    t.text     "grant"
    t.text     "lab"
    t.text     "lab_exp_id"
    t.text     "lab_version"
    t.text     "md5sum"
    t.text     "orig_assembly"
    t.text     "project"
    t.text     "replicate"
    t.text     "set_type"
    t.text     "size"
    t.text     "sub_id"
    t.text     "table_name"
    t.text     "treatment"
    t.text     "type"
    t.text     "view"
    t.text     "filename"
    t.text     "fname"
    t.text     "url"
    t.datetime "created_at"
    t.datetime "updated_at"
  end

end
